name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk
      # - run: flutter build appbundle --dart-define=ENVIRONMENT=production --ignore-deprecation --no-tree-shake-icons
